// Code generated by hertz generator.

package user

import (
	"context"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"go-ssip/app/common/errno"
	"go-ssip/app/common/tools"
	g "go-ssip/app/service/api/http/global"
	"net/http"

	"github.com/cloudwego/hertz/pkg/app"
	kuser "go-ssip/app/common/kitex_gen/user"
	huser "go-ssip/app/service/api/http/biz/model/user"
)

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req huser.LoginReq
	resp := new(kuser.AuthResp)
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(http.StatusBadRequest, err.Error())
		return
	}
	if req.Username == "" || req.Password == "" {
		resp.BaseResp = tools.BuildBaseResp(errno.ParamsErr)
		c.JSON(http.StatusBadRequest, resp)
		return
	}

	res, err := g.GlobalUserClient.Auth(ctx, &kuser.AuthReq{
		Username: req.Username,
		Password: req.Password,
	})
	if err != nil {
		hlog.Error("rpc user service err", err)
		resp.BaseResp = tools.BuildBaseResp(errno.ServiceErr)
		c.JSON(http.StatusInternalServerError, resp)
		return
	}

	err = tools.ParseBaseResp(res.BaseResp)
	if err != nil {
		if err == errno.RecordNotFound {
			c.JSON(http.StatusOK, "no such user")
		} else if err == errno.BadRequest {
			c.JSON(http.StatusBadRequest, "password incorrect")
		}
		c.JSON(http.StatusInternalServerError, err)
		return
	}

	c.JSON(http.StatusOK, res)
}
