// Code generated by thriftgo (0.3.0). DO NOT EDIT.

package msg

import (
	"context"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"go-ssip/app/common/kitex_gen/base"
)

type SendMsgReq struct {
	Msg *Msg `thrift:"msg,1" frugal:"1,default,Msg" json:"msg"`
}

func NewSendMsgReq() *SendMsgReq {
	return &SendMsgReq{}
}

func (p *SendMsgReq) InitDefault() {
	*p = SendMsgReq{}
}

var SendMsgReq_Msg_DEFAULT *Msg

func (p *SendMsgReq) GetMsg() (v *Msg) {
	if !p.IsSetMsg() {
		return SendMsgReq_Msg_DEFAULT
	}
	return p.Msg
}
func (p *SendMsgReq) SetMsg(val *Msg) {
	p.Msg = val
}

var fieldIDToName_SendMsgReq = map[int16]string{
	1: "msg",
}

func (p *SendMsgReq) IsSetMsg() bool {
	return p.Msg != nil
}

func (p *SendMsgReq) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SendMsgReq[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SendMsgReq) ReadField1(iprot thrift.TProtocol) error {
	p.Msg = NewMsg()
	if err := p.Msg.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *SendMsgReq) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("SendMsgReq"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SendMsgReq) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("msg", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Msg.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *SendMsgReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendMsgReq(%+v)", *p)
}

func (p *SendMsgReq) DeepEqual(ano *SendMsgReq) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Msg) {
		return false
	}
	return true
}

func (p *SendMsgReq) Field1DeepEqual(src *Msg) bool {

	if !p.Msg.DeepEqual(src) {
		return false
	}
	return true
}

type SendMsgResp struct {
	BaseResp *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
}

func NewSendMsgResp() *SendMsgResp {
	return &SendMsgResp{}
}

func (p *SendMsgResp) InitDefault() {
	*p = SendMsgResp{}
}

var SendMsgResp_BaseResp_DEFAULT *base.BaseResponse

func (p *SendMsgResp) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return SendMsgResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *SendMsgResp) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}

var fieldIDToName_SendMsgResp = map[int16]string{
	1: "base_resp",
}

func (p *SendMsgResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *SendMsgResp) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SendMsgResp[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SendMsgResp) ReadField1(iprot thrift.TProtocol) error {
	p.BaseResp = base.NewBaseResponse()
	if err := p.BaseResp.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *SendMsgResp) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("SendMsgResp"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SendMsgResp) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("base_resp", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.BaseResp.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *SendMsgResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendMsgResp(%+v)", *p)
}

func (p *SendMsgResp) DeepEqual(ano *SendMsgResp) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.BaseResp) {
		return false
	}
	return true
}

func (p *SendMsgResp) Field1DeepEqual(src *base.BaseResponse) bool {

	if !p.BaseResp.DeepEqual(src) {
		return false
	}
	return true
}

type SendGroupMsgReq struct {
	GroupMsg *GroupMsg `thrift:"group_msg,1" frugal:"1,default,GroupMsg" json:"group_msg"`
}

func NewSendGroupMsgReq() *SendGroupMsgReq {
	return &SendGroupMsgReq{}
}

func (p *SendGroupMsgReq) InitDefault() {
	*p = SendGroupMsgReq{}
}

var SendGroupMsgReq_GroupMsg_DEFAULT *GroupMsg

func (p *SendGroupMsgReq) GetGroupMsg() (v *GroupMsg) {
	if !p.IsSetGroupMsg() {
		return SendGroupMsgReq_GroupMsg_DEFAULT
	}
	return p.GroupMsg
}
func (p *SendGroupMsgReq) SetGroupMsg(val *GroupMsg) {
	p.GroupMsg = val
}

var fieldIDToName_SendGroupMsgReq = map[int16]string{
	1: "group_msg",
}

func (p *SendGroupMsgReq) IsSetGroupMsg() bool {
	return p.GroupMsg != nil
}

func (p *SendGroupMsgReq) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SendGroupMsgReq[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SendGroupMsgReq) ReadField1(iprot thrift.TProtocol) error {
	p.GroupMsg = NewGroupMsg()
	if err := p.GroupMsg.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *SendGroupMsgReq) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("SendGroupMsgReq"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SendGroupMsgReq) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("group_msg", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.GroupMsg.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *SendGroupMsgReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendGroupMsgReq(%+v)", *p)
}

func (p *SendGroupMsgReq) DeepEqual(ano *SendGroupMsgReq) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.GroupMsg) {
		return false
	}
	return true
}

func (p *SendGroupMsgReq) Field1DeepEqual(src *GroupMsg) bool {

	if !p.GroupMsg.DeepEqual(src) {
		return false
	}
	return true
}

type SendGroupMsgResp struct {
	BaseResp *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
}

func NewSendGroupMsgResp() *SendGroupMsgResp {
	return &SendGroupMsgResp{}
}

func (p *SendGroupMsgResp) InitDefault() {
	*p = SendGroupMsgResp{}
}

var SendGroupMsgResp_BaseResp_DEFAULT *base.BaseResponse

func (p *SendGroupMsgResp) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return SendGroupMsgResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *SendGroupMsgResp) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}

var fieldIDToName_SendGroupMsgResp = map[int16]string{
	1: "base_resp",
}

func (p *SendGroupMsgResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *SendGroupMsgResp) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SendGroupMsgResp[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SendGroupMsgResp) ReadField1(iprot thrift.TProtocol) error {
	p.BaseResp = base.NewBaseResponse()
	if err := p.BaseResp.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *SendGroupMsgResp) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("SendGroupMsgResp"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SendGroupMsgResp) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("base_resp", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.BaseResp.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *SendGroupMsgResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendGroupMsgResp(%+v)", *p)
}

func (p *SendGroupMsgResp) DeepEqual(ano *SendGroupMsgResp) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.BaseResp) {
		return false
	}
	return true
}

func (p *SendGroupMsgResp) Field1DeepEqual(src *base.BaseResponse) bool {

	if !p.BaseResp.DeepEqual(src) {
		return false
	}
	return true
}

type GetMsgReq struct {
	FromUser int64 `thrift:"from_user,1" frugal:"1,default,i64" json:"from_user"`
	ToUser   int64 `thrift:"to_user,2" frugal:"2,default,i64" json:"to_user"`
}

func NewGetMsgReq() *GetMsgReq {
	return &GetMsgReq{}
}

func (p *GetMsgReq) InitDefault() {
	*p = GetMsgReq{}
}

func (p *GetMsgReq) GetFromUser() (v int64) {
	return p.FromUser
}

func (p *GetMsgReq) GetToUser() (v int64) {
	return p.ToUser
}
func (p *GetMsgReq) SetFromUser(val int64) {
	p.FromUser = val
}
func (p *GetMsgReq) SetToUser(val int64) {
	p.ToUser = val
}

var fieldIDToName_GetMsgReq = map[int16]string{
	1: "from_user",
	2: "to_user",
}

func (p *GetMsgReq) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 2:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_GetMsgReq[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *GetMsgReq) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.FromUser = v
	}
	return nil
}

func (p *GetMsgReq) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.ToUser = v
	}
	return nil
}

func (p *GetMsgReq) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetMsgReq"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *GetMsgReq) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("from_user", thrift.I64, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.FromUser); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *GetMsgReq) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("to_user", thrift.I64, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.ToUser); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *GetMsgReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMsgReq(%+v)", *p)
}

func (p *GetMsgReq) DeepEqual(ano *GetMsgReq) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.FromUser) {
		return false
	}
	if !p.Field2DeepEqual(ano.ToUser) {
		return false
	}
	return true
}

func (p *GetMsgReq) Field1DeepEqual(src int64) bool {

	if p.FromUser != src {
		return false
	}
	return true
}
func (p *GetMsgReq) Field2DeepEqual(src int64) bool {

	if p.ToUser != src {
		return false
	}
	return true
}

type GetMsgResp struct {
	Msgs     []*Msg             `thrift:"msgs,1" frugal:"1,default,list<Msg>" json:"msgs"`
	BaseResp *base.BaseResponse `thrift:"base_resp,2" frugal:"2,default,base.BaseResponse" json:"base_resp"`
}

func NewGetMsgResp() *GetMsgResp {
	return &GetMsgResp{}
}

func (p *GetMsgResp) InitDefault() {
	*p = GetMsgResp{}
}

func (p *GetMsgResp) GetMsgs() (v []*Msg) {
	return p.Msgs
}

var GetMsgResp_BaseResp_DEFAULT *base.BaseResponse

func (p *GetMsgResp) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GetMsgResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetMsgResp) SetMsgs(val []*Msg) {
	p.Msgs = val
}
func (p *GetMsgResp) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}

var fieldIDToName_GetMsgResp = map[int16]string{
	1: "msgs",
	2: "base_resp",
}

func (p *GetMsgResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetMsgResp) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.LIST {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 2:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_GetMsgResp[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *GetMsgResp) ReadField1(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return err
	}
	p.Msgs = make([]*Msg, 0, size)
	for i := 0; i < size; i++ {
		_elem := NewMsg()
		if err := _elem.Read(iprot); err != nil {
			return err
		}

		p.Msgs = append(p.Msgs, _elem)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return err
	}
	return nil
}

func (p *GetMsgResp) ReadField2(iprot thrift.TProtocol) error {
	p.BaseResp = base.NewBaseResponse()
	if err := p.BaseResp.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *GetMsgResp) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetMsgResp"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *GetMsgResp) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("msgs", thrift.LIST, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Msgs)); err != nil {
		return err
	}
	for _, v := range p.Msgs {
		if err := v.Write(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteListEnd(); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *GetMsgResp) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("base_resp", thrift.STRUCT, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.BaseResp.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *GetMsgResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMsgResp(%+v)", *p)
}

func (p *GetMsgResp) DeepEqual(ano *GetMsgResp) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Msgs) {
		return false
	}
	if !p.Field2DeepEqual(ano.BaseResp) {
		return false
	}
	return true
}

func (p *GetMsgResp) Field1DeepEqual(src []*Msg) bool {

	if len(p.Msgs) != len(src) {
		return false
	}
	for i, v := range p.Msgs {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *GetMsgResp) Field2DeepEqual(src *base.BaseResponse) bool {

	if !p.BaseResp.DeepEqual(src) {
		return false
	}
	return true
}

type GetGroupMsgReq struct {
	Group int64 `thrift:"group,1" frugal:"1,default,i64" json:"group"`
}

func NewGetGroupMsgReq() *GetGroupMsgReq {
	return &GetGroupMsgReq{}
}

func (p *GetGroupMsgReq) InitDefault() {
	*p = GetGroupMsgReq{}
}

func (p *GetGroupMsgReq) GetGroup() (v int64) {
	return p.Group
}
func (p *GetGroupMsgReq) SetGroup(val int64) {
	p.Group = val
}

var fieldIDToName_GetGroupMsgReq = map[int16]string{
	1: "group",
}

func (p *GetGroupMsgReq) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_GetGroupMsgReq[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *GetGroupMsgReq) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.Group = v
	}
	return nil
}

func (p *GetGroupMsgReq) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetGroupMsgReq"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *GetGroupMsgReq) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("group", thrift.I64, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.Group); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *GetGroupMsgReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetGroupMsgReq(%+v)", *p)
}

func (p *GetGroupMsgReq) DeepEqual(ano *GetGroupMsgReq) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Group) {
		return false
	}
	return true
}

func (p *GetGroupMsgReq) Field1DeepEqual(src int64) bool {

	if p.Group != src {
		return false
	}
	return true
}

type GetGroupMsgResp struct {
	GroupMsgs []*GroupMsg        `thrift:"group_msgs,1" frugal:"1,default,list<GroupMsg>" json:"group_msgs"`
	BaseResp  *base.BaseResponse `thrift:"base_resp,2" frugal:"2,default,base.BaseResponse" json:"base_resp"`
}

func NewGetGroupMsgResp() *GetGroupMsgResp {
	return &GetGroupMsgResp{}
}

func (p *GetGroupMsgResp) InitDefault() {
	*p = GetGroupMsgResp{}
}

func (p *GetGroupMsgResp) GetGroupMsgs() (v []*GroupMsg) {
	return p.GroupMsgs
}

var GetGroupMsgResp_BaseResp_DEFAULT *base.BaseResponse

func (p *GetGroupMsgResp) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GetGroupMsgResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetGroupMsgResp) SetGroupMsgs(val []*GroupMsg) {
	p.GroupMsgs = val
}
func (p *GetGroupMsgResp) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}

var fieldIDToName_GetGroupMsgResp = map[int16]string{
	1: "group_msgs",
	2: "base_resp",
}

func (p *GetGroupMsgResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetGroupMsgResp) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.LIST {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		case 2:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_GetGroupMsgResp[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *GetGroupMsgResp) ReadField1(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return err
	}
	p.GroupMsgs = make([]*GroupMsg, 0, size)
	for i := 0; i < size; i++ {
		_elem := NewGroupMsg()
		if err := _elem.Read(iprot); err != nil {
			return err
		}

		p.GroupMsgs = append(p.GroupMsgs, _elem)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return err
	}
	return nil
}

func (p *GetGroupMsgResp) ReadField2(iprot thrift.TProtocol) error {
	p.BaseResp = base.NewBaseResponse()
	if err := p.BaseResp.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *GetGroupMsgResp) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetGroupMsgResp"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *GetGroupMsgResp) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("group_msgs", thrift.LIST, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteListBegin(thrift.STRUCT, len(p.GroupMsgs)); err != nil {
		return err
	}
	for _, v := range p.GroupMsgs {
		if err := v.Write(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteListEnd(); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *GetGroupMsgResp) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("base_resp", thrift.STRUCT, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.BaseResp.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *GetGroupMsgResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetGroupMsgResp(%+v)", *p)
}

func (p *GetGroupMsgResp) DeepEqual(ano *GetGroupMsgResp) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.GroupMsgs) {
		return false
	}
	if !p.Field2DeepEqual(ano.BaseResp) {
		return false
	}
	return true
}

func (p *GetGroupMsgResp) Field1DeepEqual(src []*GroupMsg) bool {

	if len(p.GroupMsgs) != len(src) {
		return false
	}
	for i, v := range p.GroupMsgs {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *GetGroupMsgResp) Field2DeepEqual(src *base.BaseResponse) bool {

	if !p.BaseResp.DeepEqual(src) {
		return false
	}
	return true
}

type MsgService interface {
	SendMsg(ctx context.Context, req *SendMsgReq) (r *SendMsgResp, err error)

	SendGroupMsg(ctx context.Context, req *SendGroupMsgReq) (r *SendGroupMsgResp, err error)

	GetMsg(ctx context.Context, req *GetMsgReq) (r *GetMsgResp, err error)

	GetGroupMsg(ctx context.Context, req *GetGroupMsgReq) (r *GetGroupMsgResp, err error)
}

type MsgServiceClient struct {
	c thrift.TClient
}

func NewMsgServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *MsgServiceClient {
	return &MsgServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewMsgServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *MsgServiceClient {
	return &MsgServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewMsgServiceClient(c thrift.TClient) *MsgServiceClient {
	return &MsgServiceClient{
		c: c,
	}
}

func (p *MsgServiceClient) Client_() thrift.TClient {
	return p.c
}

func (p *MsgServiceClient) SendMsg(ctx context.Context, req *SendMsgReq) (r *SendMsgResp, err error) {
	var _args MsgServiceSendMsgArgs
	_args.Req = req
	var _result MsgServiceSendMsgResult
	if err = p.Client_().Call(ctx, "sendMsg", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
func (p *MsgServiceClient) SendGroupMsg(ctx context.Context, req *SendGroupMsgReq) (r *SendGroupMsgResp, err error) {
	var _args MsgServiceSendGroupMsgArgs
	_args.Req = req
	var _result MsgServiceSendGroupMsgResult
	if err = p.Client_().Call(ctx, "sendGroupMsg", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
func (p *MsgServiceClient) GetMsg(ctx context.Context, req *GetMsgReq) (r *GetMsgResp, err error) {
	var _args MsgServiceGetMsgArgs
	_args.Req = req
	var _result MsgServiceGetMsgResult
	if err = p.Client_().Call(ctx, "getMsg", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
func (p *MsgServiceClient) GetGroupMsg(ctx context.Context, req *GetGroupMsgReq) (r *GetGroupMsgResp, err error) {
	var _args MsgServiceGetGroupMsgArgs
	_args.Req = req
	var _result MsgServiceGetGroupMsgResult
	if err = p.Client_().Call(ctx, "getGroupMsg", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

type MsgServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      MsgService
}

func (p *MsgServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *MsgServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *MsgServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewMsgServiceProcessor(handler MsgService) *MsgServiceProcessor {
	self := &MsgServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self.AddToProcessorMap("sendMsg", &msgServiceProcessorSendMsg{handler: handler})
	self.AddToProcessorMap("sendGroupMsg", &msgServiceProcessorSendGroupMsg{handler: handler})
	self.AddToProcessorMap("getMsg", &msgServiceProcessorGetMsg{handler: handler})
	self.AddToProcessorMap("getGroupMsg", &msgServiceProcessorGetGroupMsg{handler: handler})
	return self
}
func (p *MsgServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush(ctx)
	return false, x
}

type msgServiceProcessorSendMsg struct {
	handler MsgService
}

func (p *msgServiceProcessorSendMsg) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := MsgServiceSendMsgArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("sendMsg", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := MsgServiceSendMsgResult{}
	var retval *SendMsgResp
	if retval, err2 = p.handler.SendMsg(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing sendMsg: "+err2.Error())
		oprot.WriteMessageBegin("sendMsg", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("sendMsg", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type msgServiceProcessorSendGroupMsg struct {
	handler MsgService
}

func (p *msgServiceProcessorSendGroupMsg) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := MsgServiceSendGroupMsgArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("sendGroupMsg", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := MsgServiceSendGroupMsgResult{}
	var retval *SendGroupMsgResp
	if retval, err2 = p.handler.SendGroupMsg(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing sendGroupMsg: "+err2.Error())
		oprot.WriteMessageBegin("sendGroupMsg", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("sendGroupMsg", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type msgServiceProcessorGetMsg struct {
	handler MsgService
}

func (p *msgServiceProcessorGetMsg) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := MsgServiceGetMsgArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("getMsg", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := MsgServiceGetMsgResult{}
	var retval *GetMsgResp
	if retval, err2 = p.handler.GetMsg(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing getMsg: "+err2.Error())
		oprot.WriteMessageBegin("getMsg", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("getMsg", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type msgServiceProcessorGetGroupMsg struct {
	handler MsgService
}

func (p *msgServiceProcessorGetGroupMsg) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := MsgServiceGetGroupMsgArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("getGroupMsg", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := MsgServiceGetGroupMsgResult{}
	var retval *GetGroupMsgResp
	if retval, err2 = p.handler.GetGroupMsg(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing getGroupMsg: "+err2.Error())
		oprot.WriteMessageBegin("getGroupMsg", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("getGroupMsg", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type MsgServiceSendMsgArgs struct {
	Req *SendMsgReq `thrift:"req,1" frugal:"1,default,SendMsgReq" json:"req"`
}

func NewMsgServiceSendMsgArgs() *MsgServiceSendMsgArgs {
	return &MsgServiceSendMsgArgs{}
}

func (p *MsgServiceSendMsgArgs) InitDefault() {
	*p = MsgServiceSendMsgArgs{}
}

var MsgServiceSendMsgArgs_Req_DEFAULT *SendMsgReq

func (p *MsgServiceSendMsgArgs) GetReq() (v *SendMsgReq) {
	if !p.IsSetReq() {
		return MsgServiceSendMsgArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *MsgServiceSendMsgArgs) SetReq(val *SendMsgReq) {
	p.Req = val
}

var fieldIDToName_MsgServiceSendMsgArgs = map[int16]string{
	1: "req",
}

func (p *MsgServiceSendMsgArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MsgServiceSendMsgArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_MsgServiceSendMsgArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *MsgServiceSendMsgArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = NewSendMsgReq()
	if err := p.Req.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *MsgServiceSendMsgArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("sendMsg_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *MsgServiceSendMsgArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *MsgServiceSendMsgArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MsgServiceSendMsgArgs(%+v)", *p)
}

func (p *MsgServiceSendMsgArgs) DeepEqual(ano *MsgServiceSendMsgArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *MsgServiceSendMsgArgs) Field1DeepEqual(src *SendMsgReq) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

type MsgServiceSendMsgResult struct {
	Success *SendMsgResp `thrift:"success,0,optional" frugal:"0,optional,SendMsgResp" json:"success,omitempty"`
}

func NewMsgServiceSendMsgResult() *MsgServiceSendMsgResult {
	return &MsgServiceSendMsgResult{}
}

func (p *MsgServiceSendMsgResult) InitDefault() {
	*p = MsgServiceSendMsgResult{}
}

var MsgServiceSendMsgResult_Success_DEFAULT *SendMsgResp

func (p *MsgServiceSendMsgResult) GetSuccess() (v *SendMsgResp) {
	if !p.IsSetSuccess() {
		return MsgServiceSendMsgResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MsgServiceSendMsgResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendMsgResp)
}

var fieldIDToName_MsgServiceSendMsgResult = map[int16]string{
	0: "success",
}

func (p *MsgServiceSendMsgResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MsgServiceSendMsgResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_MsgServiceSendMsgResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *MsgServiceSendMsgResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = NewSendMsgResp()
	if err := p.Success.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *MsgServiceSendMsgResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("sendMsg_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *MsgServiceSendMsgResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *MsgServiceSendMsgResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MsgServiceSendMsgResult(%+v)", *p)
}

func (p *MsgServiceSendMsgResult) DeepEqual(ano *MsgServiceSendMsgResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *MsgServiceSendMsgResult) Field0DeepEqual(src *SendMsgResp) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}

type MsgServiceSendGroupMsgArgs struct {
	Req *SendGroupMsgReq `thrift:"req,1" frugal:"1,default,SendGroupMsgReq" json:"req"`
}

func NewMsgServiceSendGroupMsgArgs() *MsgServiceSendGroupMsgArgs {
	return &MsgServiceSendGroupMsgArgs{}
}

func (p *MsgServiceSendGroupMsgArgs) InitDefault() {
	*p = MsgServiceSendGroupMsgArgs{}
}

var MsgServiceSendGroupMsgArgs_Req_DEFAULT *SendGroupMsgReq

func (p *MsgServiceSendGroupMsgArgs) GetReq() (v *SendGroupMsgReq) {
	if !p.IsSetReq() {
		return MsgServiceSendGroupMsgArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *MsgServiceSendGroupMsgArgs) SetReq(val *SendGroupMsgReq) {
	p.Req = val
}

var fieldIDToName_MsgServiceSendGroupMsgArgs = map[int16]string{
	1: "req",
}

func (p *MsgServiceSendGroupMsgArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MsgServiceSendGroupMsgArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_MsgServiceSendGroupMsgArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *MsgServiceSendGroupMsgArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = NewSendGroupMsgReq()
	if err := p.Req.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *MsgServiceSendGroupMsgArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("sendGroupMsg_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *MsgServiceSendGroupMsgArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *MsgServiceSendGroupMsgArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MsgServiceSendGroupMsgArgs(%+v)", *p)
}

func (p *MsgServiceSendGroupMsgArgs) DeepEqual(ano *MsgServiceSendGroupMsgArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *MsgServiceSendGroupMsgArgs) Field1DeepEqual(src *SendGroupMsgReq) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

type MsgServiceSendGroupMsgResult struct {
	Success *SendGroupMsgResp `thrift:"success,0,optional" frugal:"0,optional,SendGroupMsgResp" json:"success,omitempty"`
}

func NewMsgServiceSendGroupMsgResult() *MsgServiceSendGroupMsgResult {
	return &MsgServiceSendGroupMsgResult{}
}

func (p *MsgServiceSendGroupMsgResult) InitDefault() {
	*p = MsgServiceSendGroupMsgResult{}
}

var MsgServiceSendGroupMsgResult_Success_DEFAULT *SendGroupMsgResp

func (p *MsgServiceSendGroupMsgResult) GetSuccess() (v *SendGroupMsgResp) {
	if !p.IsSetSuccess() {
		return MsgServiceSendGroupMsgResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MsgServiceSendGroupMsgResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendGroupMsgResp)
}

var fieldIDToName_MsgServiceSendGroupMsgResult = map[int16]string{
	0: "success",
}

func (p *MsgServiceSendGroupMsgResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MsgServiceSendGroupMsgResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_MsgServiceSendGroupMsgResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *MsgServiceSendGroupMsgResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = NewSendGroupMsgResp()
	if err := p.Success.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *MsgServiceSendGroupMsgResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("sendGroupMsg_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *MsgServiceSendGroupMsgResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *MsgServiceSendGroupMsgResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MsgServiceSendGroupMsgResult(%+v)", *p)
}

func (p *MsgServiceSendGroupMsgResult) DeepEqual(ano *MsgServiceSendGroupMsgResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *MsgServiceSendGroupMsgResult) Field0DeepEqual(src *SendGroupMsgResp) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}

type MsgServiceGetMsgArgs struct {
	Req *GetMsgReq `thrift:"req,1" frugal:"1,default,GetMsgReq" json:"req"`
}

func NewMsgServiceGetMsgArgs() *MsgServiceGetMsgArgs {
	return &MsgServiceGetMsgArgs{}
}

func (p *MsgServiceGetMsgArgs) InitDefault() {
	*p = MsgServiceGetMsgArgs{}
}

var MsgServiceGetMsgArgs_Req_DEFAULT *GetMsgReq

func (p *MsgServiceGetMsgArgs) GetReq() (v *GetMsgReq) {
	if !p.IsSetReq() {
		return MsgServiceGetMsgArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *MsgServiceGetMsgArgs) SetReq(val *GetMsgReq) {
	p.Req = val
}

var fieldIDToName_MsgServiceGetMsgArgs = map[int16]string{
	1: "req",
}

func (p *MsgServiceGetMsgArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MsgServiceGetMsgArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_MsgServiceGetMsgArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *MsgServiceGetMsgArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = NewGetMsgReq()
	if err := p.Req.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *MsgServiceGetMsgArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("getMsg_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *MsgServiceGetMsgArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *MsgServiceGetMsgArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MsgServiceGetMsgArgs(%+v)", *p)
}

func (p *MsgServiceGetMsgArgs) DeepEqual(ano *MsgServiceGetMsgArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *MsgServiceGetMsgArgs) Field1DeepEqual(src *GetMsgReq) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

type MsgServiceGetMsgResult struct {
	Success *GetMsgResp `thrift:"success,0,optional" frugal:"0,optional,GetMsgResp" json:"success,omitempty"`
}

func NewMsgServiceGetMsgResult() *MsgServiceGetMsgResult {
	return &MsgServiceGetMsgResult{}
}

func (p *MsgServiceGetMsgResult) InitDefault() {
	*p = MsgServiceGetMsgResult{}
}

var MsgServiceGetMsgResult_Success_DEFAULT *GetMsgResp

func (p *MsgServiceGetMsgResult) GetSuccess() (v *GetMsgResp) {
	if !p.IsSetSuccess() {
		return MsgServiceGetMsgResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MsgServiceGetMsgResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetMsgResp)
}

var fieldIDToName_MsgServiceGetMsgResult = map[int16]string{
	0: "success",
}

func (p *MsgServiceGetMsgResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MsgServiceGetMsgResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_MsgServiceGetMsgResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *MsgServiceGetMsgResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = NewGetMsgResp()
	if err := p.Success.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *MsgServiceGetMsgResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("getMsg_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *MsgServiceGetMsgResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *MsgServiceGetMsgResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MsgServiceGetMsgResult(%+v)", *p)
}

func (p *MsgServiceGetMsgResult) DeepEqual(ano *MsgServiceGetMsgResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *MsgServiceGetMsgResult) Field0DeepEqual(src *GetMsgResp) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}

type MsgServiceGetGroupMsgArgs struct {
	Req *GetGroupMsgReq `thrift:"req,1" frugal:"1,default,GetGroupMsgReq" json:"req"`
}

func NewMsgServiceGetGroupMsgArgs() *MsgServiceGetGroupMsgArgs {
	return &MsgServiceGetGroupMsgArgs{}
}

func (p *MsgServiceGetGroupMsgArgs) InitDefault() {
	*p = MsgServiceGetGroupMsgArgs{}
}

var MsgServiceGetGroupMsgArgs_Req_DEFAULT *GetGroupMsgReq

func (p *MsgServiceGetGroupMsgArgs) GetReq() (v *GetGroupMsgReq) {
	if !p.IsSetReq() {
		return MsgServiceGetGroupMsgArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *MsgServiceGetGroupMsgArgs) SetReq(val *GetGroupMsgReq) {
	p.Req = val
}

var fieldIDToName_MsgServiceGetGroupMsgArgs = map[int16]string{
	1: "req",
}

func (p *MsgServiceGetGroupMsgArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MsgServiceGetGroupMsgArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_MsgServiceGetGroupMsgArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *MsgServiceGetGroupMsgArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = NewGetGroupMsgReq()
	if err := p.Req.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *MsgServiceGetGroupMsgArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("getGroupMsg_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *MsgServiceGetGroupMsgArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *MsgServiceGetGroupMsgArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MsgServiceGetGroupMsgArgs(%+v)", *p)
}

func (p *MsgServiceGetGroupMsgArgs) DeepEqual(ano *MsgServiceGetGroupMsgArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *MsgServiceGetGroupMsgArgs) Field1DeepEqual(src *GetGroupMsgReq) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

type MsgServiceGetGroupMsgResult struct {
	Success *GetGroupMsgResp `thrift:"success,0,optional" frugal:"0,optional,GetGroupMsgResp" json:"success,omitempty"`
}

func NewMsgServiceGetGroupMsgResult() *MsgServiceGetGroupMsgResult {
	return &MsgServiceGetGroupMsgResult{}
}

func (p *MsgServiceGetGroupMsgResult) InitDefault() {
	*p = MsgServiceGetGroupMsgResult{}
}

var MsgServiceGetGroupMsgResult_Success_DEFAULT *GetGroupMsgResp

func (p *MsgServiceGetGroupMsgResult) GetSuccess() (v *GetGroupMsgResp) {
	if !p.IsSetSuccess() {
		return MsgServiceGetGroupMsgResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MsgServiceGetGroupMsgResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetGroupMsgResp)
}

var fieldIDToName_MsgServiceGetGroupMsgResult = map[int16]string{
	0: "success",
}

func (p *MsgServiceGetGroupMsgResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MsgServiceGetGroupMsgResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_MsgServiceGetGroupMsgResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *MsgServiceGetGroupMsgResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = NewGetGroupMsgResp()
	if err := p.Success.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *MsgServiceGetGroupMsgResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("getGroupMsg_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *MsgServiceGetGroupMsgResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *MsgServiceGetGroupMsgResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MsgServiceGetGroupMsgResult(%+v)", *p)
}

func (p *MsgServiceGetGroupMsgResult) DeepEqual(ano *MsgServiceGetGroupMsgResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *MsgServiceGetGroupMsgResult) Field0DeepEqual(src *GetGroupMsgResp) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
